# Generated by Django 5.2 on 2025-04-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('funciones', models.TextField()),
                ('horario', models.CharField(max_length=500)),
                ('requisitos', models.TextField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
