# Generated by Django 5.2.1 on 2025-06-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0002_cargo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='cargo'),
        ),
    ]
