# Generated by Django 5.2.1 on 2025-06-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0003_cargo_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos'),
        ),
    ]
