# Generated by Django 4.0.6 on 2025-06-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresas', '0004_alter_cargo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('destinatario', models.EmailField(max_length=254)),
                ('asunto', models.TextField(max_length=250)),
                ('mensaje', models.TextField(max_length=250)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_adjuntos/')),
            ],
        ),
    ]
